import { Theme } from "../tokens.slint";

export component Separator {
    in property <string> orientation: "horizontal"; // "horizontal" or "vertical"
    in property <length> thickness: 1px;
    
    horizontal-stretch: root.orientation == "horizontal" ? 1 : 0;
    vertical-stretch: root.orientation == "vertical" ? 1 : 0;
    
    min-width: root.orientation == "vertical" ? root.thickness : 0px;
    max-width: root.orientation == "vertical" ? root.thickness : 99999px;
    
    min-height: root.orientation == "horizontal" ? root.thickness : 0px;
    max-height: root.orientation == "horizontal" ? root.thickness : 99999px;
    
    Rectangle {
        width: 100%;
        height: 100%;
        background: Theme.palette.border;
    }
}
