import { Theme } from "../tokens.slint";

export component Tooltip {
    in property <string> text: "";
    
    width: 100%;
    height: 100%;
    
    @children
    
    ta := TouchArea {
        width: 100%;
        height: 100%;
    }
    
    if (ta.has-hover) : PopupWindow {
        x: 0;
        y: ta.height + Theme.spacing.xs;
        
        Rectangle {
            border-radius: Theme.spacing.xs;
            background: Theme.palette.text_primary; // inverted for tooltip
            
            HorizontalLayout {
                padding: Theme.spacing.sm;
                Text {
                    text: root.text;
                    font-family: Theme.typography.font_family;
                    font-size: Theme.typography.caption_size;
                    color: Theme.palette.surface;
                }
            }
        }
    }
}
