import { Theme } from "../tokens.slint";

export component CircularLayout {
    in property <length> radius: 100px;
    
    width: radius * 2;
    height: radius * 2;

    Rectangle {
        width: 100%;
        height: 100%;
        border-radius: parent.width / 2;
        border-width: 1px;
        border-color: Theme.palette.border;
        background: transparent;

        @children
    }
}
